# Server Configuration
server:
  port: 8761 #Standard Eureka port

# Application Name
spring:
  application:
    name: eureka_server

# Eureka Configuration
eureka:
  client:
     # Should this Eureka Server register itself? No (it's the registry itself!)
     register-with-eureka: false
     # Should it fetch registry info from other Eureka servers? NO (standalone mode)
     fetch-registry: false
     service-url:
       defaultZone: http://localhost:8761/eureka/

  server:
     # Disable self-preservation mode in development (keeps removing dead services)
     enable-self-preservation: false
     # How often to check if services are alive (milliseconds)
     eviction-interval-timer-in-ms: 3000

#Logging
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
