server:
  port: 8081

spring:
  application:
    name: auth-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: Malik@1
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update #Auto-create/update tables (use 'validate' in production!)
    show-sql: true # Print SQL queries (debug only)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true


# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true;
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


# JWT Configuration
jwt:
  secret: MySecretKeyForJWTTokenGenerationMustBe256BitsLong12345
  expiration: 86400000


# Logging
logging:
  level:
    com.bookstore.auth: DEBUG
    org.hibernate.SQL: DEBUG